// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Projetar.Web.Data;

#nullable disable

namespace Projetar.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260923205058_RenomeiaBiblicalParaSubtitulo")]
    partial class RenomeiaBiblicalParaSubtitulo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Projetar.Web.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Cpf")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("DataCadastro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("Estado")
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Municipio")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<bool>("PerfilCompleto")
                        .HasColumnType("boolean");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefone")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Projetar.Web.Models.BannerSugestao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CaminhoImagem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DataModeracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("MotivoRejeicao")
                        .HasColumnType("text");

                    b.Property<string>("RevisadoPorUsuarioId")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("RevisadoPorUsuarioId");

                    b.HasIndex("Status");

                    b.HasIndex("UsuarioId");

                    b.ToTable("BannerSugestoes");
                });

            modelBuilder.Entity("Projetar.Web.Models.Comentario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ComentarioPaiId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DataEdicao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Removido")
                        .HasColumnType("boolean");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ComentarioPaiId");

                    b.HasIndex("ItemId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Comentarios");
                });

            modelBuilder.Entity("Projetar.Web.Models.Documento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CaminhoArmazenado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DataModeracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DataUpload")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("MotivoRejeicao")
                        .HasColumnType("text");

                    b.Property<string>("NomeOriginal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RevisadoPorUsuarioId")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<long>("TamanhoBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("RevisadoPorUsuarioId");

                    b.HasIndex("Status");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Documentos");
                });

            modelBuilder.Entity("Projetar.Web.Models.EmailConfirmationCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CodigoHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiraEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Tentativas")
                        .HasColumnType("integer");

                    b.Property<bool>("Usado")
                        .HasColumnType("boolean");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "Usado");

                    b.ToTable("EmailConfirmationCodes");
                });

            modelBuilder.Entity("Projetar.Web.Models.EscopoModeracao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdicionadoPorUsuarioId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<int?>("MandamentoId")
                        .HasColumnType("integer");

                    b.Property<int>("TipoEscopo")
                        .HasColumnType("integer");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AdicionadoPorUsuarioId");

                    b.HasIndex("ItemId");

                    b.HasIndex("MandamentoId");

                    b.HasIndex("UsuarioId", "TipoEscopo", "MandamentoId", "ItemId")
                        .IsUnique();

                    b.ToTable("EscoposModeracao");
                });

            modelBuilder.Entity("Projetar.Web.Models.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BannerImagem")
                        .HasColumnType("text");

                    b.Property<string>("Corpo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CriadoPorUsuarioId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DataModeracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MandamentoId")
                        .HasColumnType("integer");

                    b.Property<string>("MotivoRejeicao")
                        .HasColumnType("text");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.Property<string>("RevisadoPorUsuarioId")
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Tags")
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Visivel")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CriadoPorUsuarioId");

                    b.HasIndex("MandamentoId");

                    b.HasIndex("RevisadoPorUsuarioId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("Itens");
                });

            modelBuilder.Entity("Projetar.Web.Models.ItemRevisao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AutorUsuarioId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ComentarioDaModeracao")
                        .HasColumnType("text");

                    b.Property<string>("ComentarioDaMudanca")
                        .HasColumnType("text");

                    b.Property<string>("CorpoAnterior")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CorpoAprovado")
                        .HasColumnType("text");

                    b.Property<string>("CorpoNovo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DataModeracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DataRevisao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("MotivoRejeicao")
                        .HasColumnType("text");

                    b.Property<string>("RevisadoPorUsuarioId")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AutorUsuarioId");

                    b.HasIndex("ItemId");

                    b.HasIndex("RevisadoPorUsuarioId");

                    b.HasIndex("Status");

                    b.ToTable("ItemRevisoes");
                });

            modelBuilder.Entity("Projetar.Web.Models.ItemRevisaoApoio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ItemRevisaoId")
                        .HasColumnType("uuid");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("ItemRevisaoId", "UsuarioId")
                        .IsUnique();

                    b.ToTable("ItemRevisaoApoios");
                });

            modelBuilder.Entity("Projetar.Web.Models.Mandamento", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Intro")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.Property<string>("Secular")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Subtitulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Visivel")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Ordem");

                    b.ToTable("Mandamentos");
                });

            modelBuilder.Entity("Projetar.Web.Models.MensagemModeracao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlvoId")
                        .HasColumnType("uuid");

                    b.Property<string>("AutorUsuarioId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TipoAlvo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AutorUsuarioId");

                    b.HasIndex("ItemId");

                    b.HasIndex("TipoAlvo", "AlvoId");

                    b.ToTable("MensagensModeracao");
                });

            modelBuilder.Entity("Projetar.Web.Models.Notificacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DataLeitura")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Lida")
                        .HasColumnType("boolean");

                    b.Property<string>("LinkUrl")
                        .HasColumnType("text");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UsuarioDestinoId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UsuarioOrigemId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("UsuarioOrigemId");

                    b.HasIndex("UsuarioDestinoId", "Lida");

                    b.ToTable("Notificacoes");
                });

            modelBuilder.Entity("Projetar.Web.Models.PasswordResetCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CodigoHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiraEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Tentativas")
                        .HasColumnType("integer");

                    b.Property<bool>("Usado")
                        .HasColumnType("boolean");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "Usado");

                    b.ToTable("PasswordResetCodes");
                });

            modelBuilder.Entity("Projetar.Web.Models.Referencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DataModeracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("MotivoRejeicao")
                        .HasColumnType("text");

                    b.Property<string>("RevisadoPorUsuarioId")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("RevisadoPorUsuarioId");

                    b.HasIndex("Status");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Referencias");
                });

            modelBuilder.Entity("Projetar.Web.Models.TagSugestao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DataModeracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("MotivoRejeicao")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RevisadoPorUsuarioId")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("RevisadoPorUsuarioId");

                    b.HasIndex("Status");

                    b.HasIndex("UsuarioId");

                    b.ToTable("TagSugestoes");
                });

            modelBuilder.Entity("Projetar.Web.Models.Voto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Estrelas")
                        .HasColumnType("integer");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Observacao")
                        .HasColumnType("text");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("ItemId", "UsuarioId")
                        .IsUnique();

                    b.ToTable("Votos");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Projetar.Web.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Projetar.Web.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Projetar.Web.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Projetar.Web.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Projetar.Web.Models.BannerSugestao", b =>
                {
                    b.HasOne("Projetar.Web.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Projetar.Web.Models.ApplicationUser", "RevisadoPorUsuario")
                        .WithMany()
                        .HasForeignKey("RevisadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Projetar.Web.Models.ApplicationUser", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("RevisadoPorUsuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Projetar.Web.Models.Comentario", b =>
                {
                    b.HasOne("Projetar.Web.Models.Comentario", "ComentarioPai")
                        .WithMany("Respostas")
                        .HasForeignKey("ComentarioPaiId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Projetar.Web.Models.Item", "Item")
                        .WithMany("Comentarios")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Projetar.Web.Models.ApplicationUser", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ComentarioPai");

                    b.Navigation("Item");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Projetar.Web.Models.Documento", b =>
                {
                    b.HasOne("Projetar.Web.Models.Item", "Item")
                        .WithMany("Documentos")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Projetar.Web.Models.ApplicationUser", "RevisadoPorUsuario")
                        .WithMany()
                        .HasForeignKey("RevisadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Projetar.Web.Models.ApplicationUser", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("RevisadoPorUsuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Projetar.Web.Models.EmailConfirmationCode", b =>
                {
                    b.HasOne("Projetar.Web.Models.ApplicationUser", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Projetar.Web.Models.EscopoModeracao", b =>
                {
                    b.HasOne("Projetar.Web.Models.ApplicationUser", "AdicionadoPorUsuario")
                        .WithMany()
                        .HasForeignKey("AdicionadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Projetar.Web.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Projetar.Web.Models.Mandamento", "Mandamento")
                        .WithMany()
                        .HasForeignKey("MandamentoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Projetar.Web.Models.ApplicationUser", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdicionadoPorUsuario");

                    b.Navigation("Item");

                    b.Navigation("Mandamento");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Projetar.Web.Models.Item", b =>
                {
                    b.HasOne("Projetar.Web.Models.ApplicationUser", "CriadoPorUsuario")
                        .WithMany()
                        .HasForeignKey("CriadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Projetar.Web.Models.Mandamento", "Mandamento")
                        .WithMany("Itens")
                        .HasForeignKey("MandamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Projetar.Web.Models.ApplicationUser", "RevisadoPorUsuario")
                        .WithMany()
                        .HasForeignKey("RevisadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CriadoPorUsuario");

                    b.Navigation("Mandamento");

                    b.Navigation("RevisadoPorUsuario");
                });

            modelBuilder.Entity("Projetar.Web.Models.ItemRevisao", b =>
                {
                    b.HasOne("Projetar.Web.Models.ApplicationUser", "AutorUsuario")
                        .WithMany()
                        .HasForeignKey("AutorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Projetar.Web.Models.Item", "Item")
                        .WithMany("Revisoes")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Projetar.Web.Models.ApplicationUser", "RevisadoPorUsuario")
                        .WithMany()
                        .HasForeignKey("RevisadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AutorUsuario");

                    b.Navigation("Item");

                    b.Navigation("RevisadoPorUsuario");
                });

            modelBuilder.Entity("Projetar.Web.Models.ItemRevisaoApoio", b =>
                {
                    b.HasOne("Projetar.Web.Models.ItemRevisao", "ItemRevisao")
                        .WithMany("Apoios")
                        .HasForeignKey("ItemRevisaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Projetar.Web.Models.ApplicationUser", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemRevisao");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Projetar.Web.Models.MensagemModeracao", b =>
                {
                    b.HasOne("Projetar.Web.Models.ApplicationUser", "AutorUsuario")
                        .WithMany()
                        .HasForeignKey("AutorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Projetar.Web.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AutorUsuario");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Projetar.Web.Models.Notificacao", b =>
                {
                    b.HasOne("Projetar.Web.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Projetar.Web.Models.ApplicationUser", "UsuarioDestino")
                        .WithMany()
                        .HasForeignKey("UsuarioDestinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Projetar.Web.Models.ApplicationUser", "UsuarioOrigem")
                        .WithMany()
                        .HasForeignKey("UsuarioOrigemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Item");

                    b.Navigation("UsuarioDestino");

                    b.Navigation("UsuarioOrigem");
                });

            modelBuilder.Entity("Projetar.Web.Models.PasswordResetCode", b =>
                {
                    b.HasOne("Projetar.Web.Models.ApplicationUser", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Projetar.Web.Models.Referencia", b =>
                {
                    b.HasOne("Projetar.Web.Models.Item", "Item")
                        .WithMany("Referencias")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Projetar.Web.Models.ApplicationUser", "RevisadoPorUsuario")
                        .WithMany()
                        .HasForeignKey("RevisadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Projetar.Web.Models.ApplicationUser", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("RevisadoPorUsuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Projetar.Web.Models.TagSugestao", b =>
                {
                    b.HasOne("Projetar.Web.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Projetar.Web.Models.ApplicationUser", "RevisadoPorUsuario")
                        .WithMany()
                        .HasForeignKey("RevisadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Projetar.Web.Models.ApplicationUser", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("RevisadoPorUsuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Projetar.Web.Models.Voto", b =>
                {
                    b.HasOne("Projetar.Web.Models.Item", "Item")
                        .WithMany("Votos")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Projetar.Web.Models.ApplicationUser", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Projetar.Web.Models.Comentario", b =>
                {
                    b.Navigation("Respostas");
                });

            modelBuilder.Entity("Projetar.Web.Models.Item", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("Documentos");

                    b.Navigation("Referencias");

                    b.Navigation("Revisoes");

                    b.Navigation("Votos");
                });

            modelBuilder.Entity("Projetar.Web.Models.ItemRevisao", b =>
                {
                    b.Navigation("Apoios");
                });

            modelBuilder.Entity("Projetar.Web.Models.Mandamento", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
